# Generated by Django 6.0 on 2025-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Художественная литература'), ('textbook', 'Учебник'), ('science', 'Научная литература'), ('other', 'Другое')], default='fiction', max_length=20),
        ),
    ]
